version: "3.8"

services:

  configserver:
    image: mohangavandeoutlook/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - eazybank-network

  accounts:
    image: mohangavandeoutlook/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eazybank-network

  loans:
    image: mohangavandeoutlook/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eazybank-network

  cards:
    image: mohangavandeoutlook/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eazybank-network

networks:
  eazybank-network: